#!/bin/sh /etc/rc.common
# Vor daemon procd init script
USE_PROCD=1
START=99
STOP=15

start_service() {
	local enabled
	config_load vor
	config_get_bool enabled vor enabled 1
	[ "$enabled" = "1" ] || return 0

	procd_open_instance
	procd_set_param command /usr/bin/vor
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param file /etc/config/vor
	procd_close_instance
}

reload_service() {
	procd_send_signal vor
}
