package com.uacspoofer.mobile.ui

import com.uacspoofer.mobile.R

internal object CountryFlagResources {
    fun drawableFor(countryCode: String?): Int? = when (countryCode?.trim()?.lowercase()) {
        "ad" -> R.drawable.flag_ad
        "ae" -> R.drawable.flag_ae
        "af" -> R.drawable.flag_af
        "ag" -> R.drawable.flag_ag
        "ai" -> R.drawable.flag_ai
        "al" -> R.drawable.flag_al
        "am" -> R.drawable.flag_am
        "ao" -> R.drawable.flag_ao
        "aq" -> R.drawable.flag_aq
        "ar" -> R.drawable.flag_ar
        "as" -> R.drawable.flag_as
        "at" -> R.drawable.flag_at
        "au" -> R.drawable.flag_au
        "aw" -> R.drawable.flag_aw
        "ax" -> R.drawable.flag_ax
        "az" -> R.drawable.flag_az
        "ba" -> R.drawable.flag_ba
        "bb" -> R.drawable.flag_bb
        "bd" -> R.drawable.flag_bd
        "be" -> R.drawable.flag_be
        "bf" -> R.drawable.flag_bf
        "bg" -> R.drawable.flag_bg
        "bh" -> R.drawable.flag_bh
        "bi" -> R.drawable.flag_bi
        "bj" -> R.drawable.flag_bj
        "bl" -> R.drawable.flag_bl
        "bm" -> R.drawable.flag_bm
        "bn" -> R.drawable.flag_bn
        "bo" -> R.drawable.flag_bo
        "bq" -> R.drawable.flag_bq
        "br" -> R.drawable.flag_br
        "bs" -> R.drawable.flag_bs
        "bt" -> R.drawable.flag_bt
        "bv" -> R.drawable.flag_bv
        "bw" -> R.drawable.flag_bw
        "by" -> R.drawable.flag_by
        "bz" -> R.drawable.flag_bz
        "ca" -> R.drawable.flag_ca
        "cc" -> R.drawable.flag_cc
        "cd" -> R.drawable.flag_cd
        "cf" -> R.drawable.flag_cf
        "cg" -> R.drawable.flag_cg
        "ch" -> R.drawable.flag_ch
        "ci" -> R.drawable.flag_ci
        "ck" -> R.drawable.flag_ck
        "cl" -> R.drawable.flag_cl
        "cm" -> R.drawable.flag_cm
        "cn" -> R.drawable.flag_cn
        "co" -> R.drawable.flag_co
        "cr" -> R.drawable.flag_cr
        "cu" -> R.drawable.flag_cu
        "cv" -> R.drawable.flag_cv
        "cw" -> R.drawable.flag_cw
        "cx" -> R.drawable.flag_cx
        "cy" -> R.drawable.flag_cy
        "cz" -> R.drawable.flag_cz
        "de" -> R.drawable.flag_de
        "dj" -> R.drawable.flag_dj
        "dk" -> R.drawable.flag_dk
        "dm" -> R.drawable.flag_dm
        "do" -> R.drawable.flag_do
        "dz" -> R.drawable.flag_dz
        "ec" -> R.drawable.flag_ec
        "ee" -> R.drawable.flag_ee
        "eg" -> R.drawable.flag_eg
        "eh" -> R.drawable.flag_eh
        "er" -> R.drawable.flag_er
        "es" -> R.drawable.flag_es
        "et" -> R.drawable.flag_et
        "eu" -> R.drawable.flag_eu
        "fi" -> R.drawable.flag_fi
        "fj" -> R.drawable.flag_fj
        "fk" -> R.drawable.flag_fk
        "fm" -> R.drawable.flag_fm
        "fo" -> R.drawable.flag_fo
        "fr" -> R.drawable.flag_fr
        "ga" -> R.drawable.flag_ga
        "gb" -> R.drawable.flag_gb
        "gd" -> R.drawable.flag_gd
        "ge" -> R.drawable.flag_ge
        "gf" -> R.drawable.flag_gf
        "gg" -> R.drawable.flag_gg
        "gh" -> R.drawable.flag_gh
        "gi" -> R.drawable.flag_gi
        "gl" -> R.drawable.flag_gl
        "gm" -> R.drawable.flag_gm
        "gn" -> R.drawable.flag_gn
        "gp" -> R.drawable.flag_gp
        "gq" -> R.drawable.flag_gq
        "gr" -> R.drawable.flag_gr
        "gs" -> R.drawable.flag_gs
        "gt" -> R.drawable.flag_gt
        "gu" -> R.drawable.flag_gu
        "gw" -> R.drawable.flag_gw
        "gy" -> R.drawable.flag_gy
        "hk" -> R.drawable.flag_hk
        "hm" -> R.drawable.flag_hm
        "hn" -> R.drawable.flag_hn
        "hr" -> R.drawable.flag_hr
        "ht" -> R.drawable.flag_ht
        "hu" -> R.drawable.flag_hu
        "id" -> R.drawable.flag_id
        "ie" -> R.drawable.flag_ie
        "il" -> R.drawable.flag_il
        "im" -> R.drawable.flag_im
        "in" -> R.drawable.flag_in
        "io" -> R.drawable.flag_io
        "iq" -> R.drawable.flag_iq
        "ir" -> R.drawable.flag_ir
        "is" -> R.drawable.flag_is
        "it" -> R.drawable.flag_it
        "je" -> R.drawable.flag_je
        "jm" -> R.drawable.flag_jm
        "jo" -> R.drawable.flag_jo
        "jp" -> R.drawable.flag_jp
        "ke" -> R.drawable.flag_ke
        "kg" -> R.drawable.flag_kg
        "kh" -> R.drawable.flag_kh
        "ki" -> R.drawable.flag_ki
        "km" -> R.drawable.flag_km
        "kn" -> R.drawable.flag_kn
        "kp" -> R.drawable.flag_kp
        "kr" -> R.drawable.flag_kr
        "kw" -> R.drawable.flag_kw
        "ky" -> R.drawable.flag_ky
        "kz" -> R.drawable.flag_kz
        "la" -> R.drawable.flag_la
        "lb" -> R.drawable.flag_lb
        "lc" -> R.drawable.flag_lc
        "li" -> R.drawable.flag_li
        "lk" -> R.drawable.flag_lk
        "lr" -> R.drawable.flag_lr
        "ls" -> R.drawable.flag_ls
        "lt" -> R.drawable.flag_lt
        "lu" -> R.drawable.flag_lu
        "lv" -> R.drawable.flag_lv
        "ly" -> R.drawable.flag_ly
        "ma" -> R.drawable.flag_ma
        "mc" -> R.drawable.flag_mc
        "md" -> R.drawable.flag_md
        "me" -> R.drawable.flag_me
        "mf" -> R.drawable.flag_mf
        "mg" -> R.drawable.flag_mg
        "mh" -> R.drawable.flag_mh
        "mk" -> R.drawable.flag_mk
        "ml" -> R.drawable.flag_ml
        "mm" -> R.drawable.flag_mm
        "mn" -> R.drawable.flag_mn
        "mo" -> R.drawable.flag_mo
        "mp" -> R.drawable.flag_mp
        "mq" -> R.drawable.flag_mq
        "mr" -> R.drawable.flag_mr
        "ms" -> R.drawable.flag_ms
        "mt" -> R.drawable.flag_mt
        "mu" -> R.drawable.flag_mu
        "mv" -> R.drawable.flag_mv
        "mw" -> R.drawable.flag_mw
        "mx" -> R.drawable.flag_mx
        "my" -> R.drawable.flag_my
        "mz" -> R.drawable.flag_mz
        "na" -> R.drawable.flag_na
        "nc" -> R.drawable.flag_nc
        "ne" -> R.drawable.flag_ne
        "nf" -> R.drawable.flag_nf
        "ng" -> R.drawable.flag_ng
        "ni" -> R.drawable.flag_ni
        "nl" -> R.drawable.flag_nl
        "no" -> R.drawable.flag_no
        "np" -> R.drawable.flag_np
        "nr" -> R.drawable.flag_nr
        "nu" -> R.drawable.flag_nu
        "nz" -> R.drawable.flag_nz
        "om" -> R.drawable.flag_om
        "pa" -> R.drawable.flag_pa
        "pe" -> R.drawable.flag_pe
        "pf" -> R.drawable.flag_pf
        "pg" -> R.drawable.flag_pg
        "ph" -> R.drawable.flag_ph
        "pk" -> R.drawable.flag_pk
        "pl" -> R.drawable.flag_pl
        "pm" -> R.drawable.flag_pm
        "pn" -> R.drawable.flag_pn
        "pr" -> R.drawable.flag_pr
        "ps" -> R.drawable.flag_ps
        "pt" -> R.drawable.flag_pt
        "pw" -> R.drawable.flag_pw
        "py" -> R.drawable.flag_py
        "qa" -> R.drawable.flag_qa
        "re" -> R.drawable.flag_re
        "ro" -> R.drawable.flag_ro
        "rs" -> R.drawable.flag_rs
        "ru" -> R.drawable.flag_ru
        "rw" -> R.drawable.flag_rw
        "sa" -> R.drawable.flag_sa
        "sb" -> R.drawable.flag_sb
        "sc" -> R.drawable.flag_sc
        "sd" -> R.drawable.flag_sd
        "se" -> R.drawable.flag_se
        "sg" -> R.drawable.flag_sg
        "sh" -> R.drawable.flag_sh
        "si" -> R.drawable.flag_si
        "sj" -> R.drawable.flag_sj
        "sk" -> R.drawable.flag_sk
        "sl" -> R.drawable.flag_sl
        "sm" -> R.drawable.flag_sm
        "sn" -> R.drawable.flag_sn
        "so" -> R.drawable.flag_so
        "sr" -> R.drawable.flag_sr
        "ss" -> R.drawable.flag_ss
        "st" -> R.drawable.flag_st
        "sv" -> R.drawable.flag_sv
        "sx" -> R.drawable.flag_sx
        "sy" -> R.drawable.flag_sy
        "sz" -> R.drawable.flag_sz
        "tc" -> R.drawable.flag_tc
        "td" -> R.drawable.flag_td
        "tf" -> R.drawable.flag_tf
        "tg" -> R.drawable.flag_tg
        "th" -> R.drawable.flag_th
        "tj" -> R.drawable.flag_tj
        "tk" -> R.drawable.flag_tk
        "tl" -> R.drawable.flag_tl
        "tm" -> R.drawable.flag_tm
        "tn" -> R.drawable.flag_tn
        "to" -> R.drawable.flag_to
        "tr" -> R.drawable.flag_tr
        "tt" -> R.drawable.flag_tt
        "tv" -> R.drawable.flag_tv
        "tw" -> R.drawable.flag_tw
        "tz" -> R.drawable.flag_tz
        "ua" -> R.drawable.flag_ua
        "ug" -> R.drawable.flag_ug
        "um" -> R.drawable.flag_um
        "un" -> R.drawable.flag_un
        "us" -> R.drawable.flag_us
        "uy" -> R.drawable.flag_uy
        "uz" -> R.drawable.flag_uz
        "va" -> R.drawable.flag_va
        "vc" -> R.drawable.flag_vc
        "ve" -> R.drawable.flag_ve
        "vg" -> R.drawable.flag_vg
        "vi" -> R.drawable.flag_vi
        "vn" -> R.drawable.flag_vn
        "vu" -> R.drawable.flag_vu
        "wf" -> R.drawable.flag_wf
        "ws" -> R.drawable.flag_ws
        "xk" -> R.drawable.flag_xk
        "ye" -> R.drawable.flag_ye
        "yt" -> R.drawable.flag_yt
        "za" -> R.drawable.flag_za
        "zm" -> R.drawable.flag_zm
        "zw" -> R.drawable.flag_zw
        else -> null
    }
}
