package com.v2rayez.app.data.cert

import android.content.Context
import android.net.Uri
import androidx.core.content.FileProvider
import org.bouncycastle.jce.provider.BouncyCastleProvider
import org.bouncycastle.openssl.PEMKeyPair
import org.bouncycastle.openssl.PEMParser
import org.bouncycastle.openssl.jcajce.JcaPEMKeyConverter
import java.io.File
import java.io.StringReader
import java.security.KeyFactory
import java.security.MessageDigest
import java.security.PrivateKey
import java.security.cert.X509Certificate
import java.security.interfaces.RSAPrivateCrtKey
import java.security.interfaces.RSAPublicKey
import java.security.spec.PKCS8EncodedKeySpec
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

/** Outcome of [MitmCaStore.importPair]. */
sealed class MitmCaImportResult {
    data object Success : MitmCaImportResult()
    data class Failure(val reason: String) : MitmCaImportResult()
}

/**
 * Reads/writes the on-device MITM CA (cert + private key) generated by [MitmCaGenerator],
 * and exposes it for sharing (cert only) or a PC-import pack (cert + key, for desktop
 * browsers/OSes that want to trust the same CA).
 */
object MitmCaStore {

    private const val CA_DIR = "assets"
    private const val CRT_NAME = "mycert.crt"
    private const val KEY_NAME = "mycert.key"
    private const val PC_PACK_DIR = "mitm-pack"
    private const val PC_PACK_ZIP_NAME = "v2rayez-mitm-ca.zip"

    /** KeyUsage bit index for keyCertSign, per [java.security.cert.X509Certificate.getKeyUsage]. */
    private const val KEY_USAGE_KEY_CERT_SIGN = 5

    init {
        BouncyCastleInstaller.ensureInstalled()
    }

    private fun assetsDir(context: Context): File = File(context.filesDir, CA_DIR).apply { mkdirs() }

    fun crtFile(context: Context): File = File(assetsDir(context), CRT_NAME)

    fun keyFile(context: Context): File = File(assetsDir(context), KEY_NAME)

    /** True when both files exist and the cert parses as a usable, unexpired X.509 cert. */
    fun isPresent(context: Context): Boolean {
        val crt = crtFile(context)
        val key = keyFile(context)
        if (!crt.exists() || !key.exists() || crt.length() == 0L || key.length() == 0L) return false
        val cert = runCatching { CertInstaller.parse(crt.readBytes()) }.getOrNull() ?: return false
        return runCatching { cert.checkValidity() }.isSuccess
    }

    /** Colon-separated uppercase-hex SHA-256 fingerprint of the CA cert, or null if unavailable. */
    fun fingerprintSha256(context: Context): String? {
        val cert = readCert(context) ?: return null
        return sha256Fingerprint(cert)
    }

    private fun sha256Fingerprint(cert: X509Certificate): String {
        val digest = MessageDigest.getInstance("SHA-256").digest(cert.encoded)
        return digest.joinToString(":") { "%02X".format(it) }
    }

    private fun readCert(context: Context): X509Certificate? {
        val crt = crtFile(context)
        if (!crt.exists()) return null
        return runCatching { CertInstaller.parse(crt.readBytes()) }.getOrNull()
    }

    /** Content [Uri] (via the app's existing `FileProvider`) for sharing/installing the cert only. */
    fun exportCrtShareUri(context: Context): Uri? {
        val crt = crtFile(context)
        if (!crt.exists()) return null
        return runCatching {
            val stagingDir = File(context.cacheDir, "mitm-certs").apply { mkdirs() }
            val stagedCrt = File(stagingDir, CRT_NAME)
            crt.copyTo(stagedCrt, overwrite = true)
            FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", stagedCrt)
        }.getOrNull()
    }

    /** Zips cert + key into the cache dir for a "PC import pack" download; returns the zip file. */
    fun exportPcPackZip(context: Context): File? {
        val crt = crtFile(context)
        val key = keyFile(context)
        if (!crt.exists() || !key.exists()) return null

        val dir = File(context.cacheDir, PC_PACK_DIR).apply { mkdirs() }
        val zip = File(dir, PC_PACK_ZIP_NAME)
        ZipOutputStream(zip.outputStream()).use { out ->
            addZipEntry(out, CRT_NAME, crt.readBytes())
            addZipEntry(out, KEY_NAME, key.readBytes())
        }
        return zip
    }

    /** Content [Uri] for [exportPcPackZip], or null if the CA isn't present. */
    fun exportPcPackZipUri(context: Context): Uri? {
        val zip = exportPcPackZip(context) ?: return null
        return FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", zip)
    }

    private fun addZipEntry(out: ZipOutputStream, name: String, bytes: ByteArray) {
        out.putNextEntry(ZipEntry(name))
        out.write(bytes)
        out.closeEntry()
    }

    /**
     * Validates [crtBytes]/[keyBytes] as a usable CA (parseable X.509, `BasicConstraints CA:true`,
     * `KeyUsage keyCertSign`, and the key's public half matches the cert's) and, only if valid,
     * writes them over [crtFile]/[keyFile].
     */
    fun importPair(context: Context, crtBytes: ByteArray, keyBytes: ByteArray): MitmCaImportResult {
        BouncyCastleInstaller.ensureInstalled()
        val cert = CertInstaller.parse(crtBytes)
            ?: return MitmCaImportResult.Failure("Not a valid X.509 certificate")

        if (cert.basicConstraints < 0) {
            return MitmCaImportResult.Failure("Certificate is not a CA (missing BasicConstraints CA:true)")
        }

        val keyUsage = cert.keyUsage
        if (keyUsage == null || keyUsage.size <= KEY_USAGE_KEY_CERT_SIGN || !keyUsage[KEY_USAGE_KEY_CERT_SIGN]) {
            return MitmCaImportResult.Failure("Certificate KeyUsage is missing keyCertSign")
        }

        val privateKey = parsePrivateKey(keyBytes)
            ?: return MitmCaImportResult.Failure("Not a valid private key (PEM PKCS#1/PKCS#8 RSA expected)")

        if (!keyMatchesCert(privateKey, cert)) {
            return MitmCaImportResult.Failure("Private key does not match the certificate's public key")
        }

        runCatching {
            writePemFile(crtFile(context), "CERTIFICATE", cert.encoded)
            writePemFile(keyFile(context), "PRIVATE KEY", privateKey.encoded)
        }.onFailure {
            return MitmCaImportResult.Failure("Failed to write CA files: ${it.message}")
        }

        return MitmCaImportResult.Success
    }

    private fun parsePrivateKey(bytes: ByteArray): PrivateKey? = runCatching {
        val text = String(bytes, Charsets.UTF_8)
        if (text.contains("-----BEGIN")) {
            PEMParser(StringReader(text)).use { parser ->
                val converter = JcaPEMKeyConverter().setProvider(BouncyCastleProvider.PROVIDER_NAME)
                when (val obj = parser.readObject()) {
                    is PEMKeyPair -> converter.getKeyPair(obj).private
                    is org.bouncycastle.asn1.pkcs.PrivateKeyInfo -> converter.getPrivateKey(obj)
                    else -> null
                }
            }
        } else {
            KeyFactory.getInstance("RSA").generatePrivate(PKCS8EncodedKeySpec(bytes))
        }
    }.getOrNull()

    private fun keyMatchesCert(privateKey: PrivateKey, cert: X509Certificate): Boolean {
        val certPub = cert.publicKey as? RSAPublicKey ?: return false
        val priv = privateKey as? RSAPrivateCrtKey ?: return false
        return certPub.modulus == priv.modulus
    }
}
