//! AI-driven Traffic Shaper for defeating DPI behavioral analysis
//!
//! This module shapes outgoing traffic to match patterns generated by an
//! adversarial GAN (Generative Adversarial Network). The GAN is trained to
//! produce traffic patterns that are statistically indistinguishable from
//! legitimate HTTPS video streaming traffic.
//!
//! ## How It Works
//!
//! 1. The GAN generates "reference patterns" - distributions of packet sizes,
//!    inter-arrival times, and burst patterns that mimic real video streaming.
//! 2. The TrafficShaper buffers outgoing packets and releases them according
//!    to the generated pattern schedule.
//! 3. Small packets are padded to match the target size distribution.
//! 4. Inter-packet delays are adjusted to match the target timing distribution.
//!
//! ## Adaptive Behavior
//!
//! The traffic shaper is ADAPTIVE - it only shapes traffic when DPI is
//! actually detected. When no DPI is present, it operates in passthrough
//! mode with zero overhead. This is critical for user experience:
//!
//! - **No DPI detected**: Packets flow through unchanged (zero latency overhead)
//! - **Passive DPI detected**: Light shaping (subtle timing adjustments only)
//! - **Active DPI detected**: Full shaping (packet sizes + timing + bursts)
//! - **Aggressive DPI**: Maximum shaping with burst pattern injection
//!
//! ## Buffer Management
//!
//! Traffic shaping requires buffering packets to control timing, but excessive
//! buffering increases latency. The shaper uses a bounded buffer with:
//! - Maximum buffer size: 64KB (configurable)
//! - Maximum queuing delay: 200ms (configurable)
//! - Priority queue: tunnel handshake packets bypass shaping
//! - Flush mechanism: when buffer is full, oldest packets are sent immediately

use std::collections::VecDeque;
use std::sync::Arc;
use std::time::{Duration, Instant};

use rand::Rng;
use tokio::sync::RwLock;
use tracing::{debug, trace, warn};

use crate::obfuscation::{IspProfile, ObfuscationError, ThreatLevel};

/// Configuration for the traffic shaper.
#[derive(Debug, Clone)]
pub struct TrafficShaperConfig {
    /// Maximum buffer size in bytes before forced flush
    pub max_buffer_bytes: usize,
    /// Maximum queuing delay in milliseconds before forced flush
    pub max_queuing_delay_ms: u32,
    /// Target packet size distribution (min, max, mean) in bytes
    pub target_packet_size: (usize, usize, usize),
    /// Whether padding is enabled (adds bytes to match target sizes)
    pub padding_enabled: bool,
    /// Whether timing adjustment is enabled
    pub timing_enabled: bool,
    /// Whether burst injection is enabled
    pub burst_injection_enabled: bool,
    /// Shaping intensity: 0.0 = passthrough, 1.0 = maximum shaping
    pub shaping_intensity: f32,
}

impl Default for TrafficShaperConfig {
    fn default() -> Self {
        Self {
            max_buffer_bytes: 65536, // 64KB
            max_queuing_delay_ms: 200,
            target_packet_size: (200, 1500, 800),
            padding_enabled: true,
            timing_enabled: true,
            burst_injection_enabled: false,
            shaping_intensity: 0.0, // Start in passthrough mode
        }
    }
}

/// A shaped packet with timing information.
#[derive(Debug, Clone)]
pub struct ShapedPacket {
    /// Packet data (may be padded)
    pub data: Vec<u8>,
    /// When this packet should be sent relative to the previous one
    pub inter_packet_delay: Duration,
    /// Whether this is a dummy/padding packet
    pub is_dummy: bool,
    /// Priority (0 = highest, bypasses shaping; 255 = lowest)
    pub priority: u8,
}

/// A buffered packet waiting to be released.
#[derive(Debug)]
struct BufferedPacket {
    /// Original packet data
    data: Vec<u8>,
    /// Time when this packet was buffered
    enqueued_at: Instant,
    /// Priority level (0 = highest)
    priority: u8,
    /// Whether this is a handshake packet that should bypass shaping
    is_handshake: bool,
}

/// Reference traffic pattern generated by the adversarial GAN.
///
/// This struct contains statistical parameters that describe how
/// legitimate HTTPS video streaming traffic looks. The GAN trains
/// on real traffic captures and generates these parameters.
#[derive(Debug, Clone)]
pub struct TrafficPattern {
    /// Packet size distribution parameters
    /// (mean, std_dev, min, max) in bytes
    pub packet_size_dist: (f64, f64, usize, usize),
    /// Inter-arrival time distribution parameters
    /// (mean_ms, std_dev_ms, min_ms, max_ms)
    pub inter_arrival_dist: (f64, f64, f64, f64),
    /// Burst pattern: (mean_burst_size, mean_inter_burst_gap_ms)
    pub burst_pattern: (usize, f64),
    /// Ratio of small packets (<200 bytes) to total
    pub small_packet_ratio: f64,
    /// Ratio of large packets (>1000 bytes) to total
    pub large_packet_ratio: f64,
    /// Pattern name for diagnostics
    pub pattern_name: String,
}

impl TrafficPattern {
    /// Create a pattern that mimics HTTPS video streaming (e.g., YouTube, Netflix).
    pub fn video_streaming() -> Self {
        Self {
            // Video streaming has bimodal distribution:
            // - Many small ACK/control packets (~64-200 bytes)
            // - Large data packets (~1200-1500 bytes) for video chunks
            packet_size_dist: (680.0, 520.0, 40, 1500),
            inter_arrival_dist: (12.0, 18.0, 0.5, 200.0),
            burst_pattern: (15, 50.0),
            small_packet_ratio: 0.4,
            large_packet_ratio: 0.35,
            pattern_name: "https-video-streaming".to_string(),
        }
    }

    /// Create a pattern that mimics HTTPS web browsing.
    pub fn web_browsing() -> Self {
        Self {
            // Web browsing: request-response pattern
            // - Small requests (~200-500 bytes)
            // - Medium responses (~500-1400 bytes)
            packet_size_dist: (450.0, 350.0, 40, 1500),
            inter_arrival_dist: (35.0, 50.0, 1.0, 500.0),
            burst_pattern: (5, 200.0),
            small_packet_ratio: 0.5,
            large_packet_ratio: 0.2,
            pattern_name: "https-web-browsing".to_string(),
        }
    }

    /// Create a pattern that mimics HTTPS file download.
    pub fn file_download() -> Self {
        Self {
            // File downloads: sustained throughput
            // - Mostly large packets (~1400-1500 bytes)
            // - Small ACKs
            packet_size_dist: (1100.0, 400.0, 40, 1500),
            inter_arrival_dist: (5.0, 8.0, 0.1, 100.0),
            burst_pattern: (30, 20.0),
            small_packet_ratio: 0.15,
            large_packet_ratio: 0.7,
            pattern_name: "https-file-download".to_string(),
        }
    }

    /// Generate a random packet size from this distribution.
    pub fn sample_packet_size(&self) -> usize {
        let mut rng = rand::thread_rng();
        let normal: f64 = rng.gen_range(-3.0..3.0); // Approximate normal
        let size = self.packet_size_dist.0 + self.packet_size_dist.1 * normal;
        let size = size
            .max(self.packet_size_dist.2 as f64)
            .min(self.packet_size_dist.3 as f64);
        size as usize
    }

    /// Generate a random inter-arrival time from this distribution.
    pub fn sample_inter_arrival(&self) -> Duration {
        let mut rng = rand::thread_rng();
        let normal: f64 = rng.gen_range(-3.0..3.0);
        let delay = self.inter_arrival_dist.0 + self.inter_arrival_dist.1 * normal;
        let delay = delay
            .max(self.inter_arrival_dist.2)
            .min(self.inter_arrival_dist.3);
        Duration::from_micros((delay * 1000.0) as u64)
    }

    /// Generate a burst size from this distribution.
    pub fn sample_burst_size(&self) -> usize {
        let mut rng = rand::thread_rng();
        let mean = self.burst_pattern.0 as f64;
        // Poisson approximation
        let burst = mean + (rng.gen_range(-1.0..1.0) * mean.sqrt());
        burst.max(1.0) as usize
    }
}

/// The TrafficShaper buffers and shapes outgoing traffic to match
/// patterns generated by the adversarial GAN.
pub struct TrafficShaper {
    /// Current configuration
    config: TrafficShaperConfig,
    /// ISP profile for strategy selection
    isp_profile: IspProfile,
    /// Current traffic pattern
    active_pattern: TrafficPattern,
    /// Packet buffer
    buffer: VecDeque<BufferedPacket>,
    /// Current buffer size in bytes
    buffer_bytes: usize,
    /// Shaping state
    state: Arc<RwLock<ShaperState>>,
    /// Statistics
    stats: ShaperStats,
}

/// Internal state of the traffic shaper.
#[derive(Debug)]
struct ShaperState {
    /// Current shaping mode
    mode: ShapingMode,
    /// Current threat level
    threat_level: ThreatLevel,
    /// Whether the shaper is active
    active: bool,
}

/// Shaping mode determines how aggressively traffic is shaped.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ShapingMode {
    /// No shaping - packets pass through unchanged
    Passthrough,
    /// Light shaping - subtle timing adjustments only
    Light,
    /// Full shaping - packet sizes + timing
    Full,
    /// Maximum shaping - includes burst injection and padding
    Aggressive,
}

/// Statistics for the traffic shaper.
#[derive(Debug, Clone, Default)]
struct ShaperStats {
    /// Total packets shaped
    packets_shaped: u64,
    /// Total packets passed through without shaping
    packets_passthrough: u64,
    /// Total dummy packets injected
    dummy_packets_injected: u64,
    /// Total padding bytes added
    padding_bytes_added: u64,
    /// Total time spent in shaping (microseconds)
    shaping_time_us: u64,
    /// Number of buffer flushes due to overflow
    buffer_flushes: u64,
    /// Maximum buffer occupancy in bytes
    max_buffer_occupancy: usize,
}

impl TrafficShaper {
    /// Create a new TrafficShaper for the given ISP profile.
    pub fn new(isp_profile: IspProfile) -> Self {
        let pattern = Self::select_pattern(isp_profile);
        let config = TrafficShaperConfig {
            shaping_intensity: if isp_profile.needs_traffic_shaping() {
                0.5
            } else {
                0.0
            },
            ..TrafficShaperConfig::default()
        };

        Self {
            config,
            isp_profile,
            active_pattern: pattern,
            buffer: VecDeque::new(),
            buffer_bytes: 0,
            state: Arc::new(RwLock::new(ShaperState {
                mode: ShapingMode::Passthrough,
                threat_level: ThreatLevel::None,
                active: false,
            })),
            stats: ShaperStats::default(),
        }
    }

    /// Create with custom configuration.
    pub fn with_config(isp_profile: IspProfile, config: TrafficShaperConfig) -> Self {
        let pattern = Self::select_pattern(isp_profile);
        Self {
            config,
            isp_profile,
            active_pattern: pattern,
            buffer: VecDeque::new(),
            buffer_bytes: 0,
            state: Arc::new(RwLock::new(ShaperState {
                mode: ShapingMode::Passthrough,
                threat_level: ThreatLevel::None,
                active: false,
            })),
            stats: ShaperStats::default(),
        }
    }

    /// Select the best traffic pattern for the given ISP.
    fn select_pattern(isp: IspProfile) -> TrafficPattern {
        match isp {
            IspProfile::Mci | IspProfile::IranTelecom | IspProfile::Mokhtari => {
                // Aggressive DPI: use video streaming (most common, hardest to distinguish)
                TrafficPattern::video_streaming()
            }
            IspProfile::Irancell => {
                // FAVA v1: web browsing pattern sufficient
                TrafficPattern::web_browsing()
            }
            _ => {
                // Default: video streaming
                TrafficPattern::video_streaming()
            }
        }
    }

    /// Update the threat level (called by ObfuscationCoordinator).
    pub async fn update_threat_level(&mut self, level: ThreatLevel) {
        let mut state = self.state.write().await;
        let prev_mode = state.mode;
        state.threat_level = level;
        state.mode = match level {
            ThreatLevel::None => ShapingMode::Passthrough,
            ThreatLevel::Passive => ShapingMode::Light,
            ThreatLevel::ActiveV1 => ShapingMode::Full,
            ThreatLevel::ActiveV2 | ThreatLevel::CompleteBlackout => ShapingMode::Aggressive,
        };
        state.active = level.requires_obfuscation();

        if prev_mode != state.mode {
            debug!(
                "TrafficShaper mode changed: {:?} -> {:?} (threat: {:?})",
                prev_mode, state.mode, level
            );
            self.config.shaping_intensity = match state.mode {
                ShapingMode::Passthrough => 0.0,
                ShapingMode::Light => 0.3,
                ShapingMode::Full => 0.7,
                ShapingMode::Aggressive => 1.0,
            };
        }
    }

    /// Shape a packet according to the current pattern and mode.
    ///
    /// Returns a `ShapedPacket` with timing and padding information.
    /// The caller is responsible for actually sending the packet at
    /// the specified time.
    pub async fn shape_packet(&mut self, data: &[u8]) -> Result<ShapedPacket, ObfuscationError> {
        let state = self.state.read().await;

        if !state.active || state.mode == ShapingMode::Passthrough {
            self.stats.packets_passthrough += 1;
            return Ok(ShapedPacket {
                data: data.to_vec(),
                inter_packet_delay: Duration::ZERO,
                is_dummy: false,
                priority: 128,
            });
        }

        let mode = state.mode;
        drop(state);

        let start = Instant::now();
        let is_handshake = self.is_tunnel_handshake(data);
        let priority = if is_handshake { 0 } else { 128 };

        // Handshake packets bypass shaping for fast tunnel establishment
        if is_handshake {
            self.stats.packets_passthrough += 1;
            return Ok(ShapedPacket {
                data: data.to_vec(),
                inter_packet_delay: Duration::ZERO,
                is_dummy: false,
                priority: 0,
            });
        }

        let mut shaped_data = data.to_vec();
        let mut inter_delay = Duration::ZERO;
        let mut is_dummy = false;

        // Apply packet size shaping
        if mode == ShapingMode::Full || mode == ShapingMode::Aggressive {
            shaped_data = self.shape_packet_size(&shaped_data, mode)?;
        }

        // Apply timing shaping
        if mode != ShapingMode::Passthrough {
            inter_delay = self.shape_timing(mode);
        }

        // Apply burst injection (aggressive mode only)
        if mode == ShapingMode::Aggressive && self.config.burst_injection_enabled {
            self.inject_burst_packets()?;
        }

        let elapsed = start.elapsed();
        self.stats.shaping_time_us += elapsed.as_micros() as u64;
        self.stats.packets_shaped += 1;

        Ok(ShapedPacket {
            data: shaped_data,
            inter_packet_delay: inter_delay,
            is_dummy,
            priority,
        })
    }

    /// Shape packet size by padding to match target distribution.
    fn shape_packet_size(
        &mut self,
        data: &[u8],
        mode: ShapingMode,
    ) -> Result<Vec<u8>, ObfuscationError> {
        if !self.config.padding_enabled {
            return Ok(data.to_vec());
        }

        let target_size = self.active_pattern.sample_packet_size();

        if data.len() >= target_size {
            // Packet is already at or above target size - no padding needed
            return Ok(data.to_vec());
        }

        // Calculate how much padding to add
        let padding_needed = target_size - data.len();

        // In light mode, only add minimal padding
        let actual_padding = if mode == ShapingMode::Light {
            padding_needed.min(32) // Max 32 bytes in light mode
        } else {
            padding_needed
        };

        let mut padded = data.to_vec();

        // Add padding with a length field so the receiver can strip it
        // Padding format: [padding_data] [2-byte padding_length]
        padded.resize(padded.len() + actual_padding, 0);

        // Fill padding with random data (looks like encrypted content)
        let mut rng = rand::thread_rng();
        for byte in padded.iter_mut().skip(data.len()) {
            *byte = rng.gen();
        }

        // Store padding length in last 2 bytes
        let padding_len_bytes = (actual_padding as u16).to_be_bytes();
        let len = padded.len();
        padded[len - 2] = padding_len_bytes[0];
        padded[len - 1] = padding_len_bytes[1];

        self.stats.padding_bytes_added += actual_padding as u64;

        Ok(padded)
    }

    /// Calculate the inter-packet delay for timing shaping.
    fn shape_timing(&self, mode: ShapingMode) -> Duration {
        let base_delay = self.active_pattern.sample_inter_arrival();

        match mode {
            ShapingMode::Light => {
                // Light mode: scale down delays
                base_delay.mul_f64(0.3 * self.config.shaping_intensity as f64)
            }
            ShapingMode::Full => {
                // Full mode: use pattern delays directly
                base_delay.mul_f64(self.config.shaping_intensity as f64)
            }
            ShapingMode::Aggressive => {
                // Aggressive: full pattern delays + occasional longer gaps
                let mut rng = rand::thread_rng();
                if rng.gen_bool(0.1) {
                    // 10% chance of longer gap (mimics video buffering)
                    base_delay * 3
                } else {
                    base_delay
                }
            }
            ShapingMode::Passthrough => Duration::ZERO,
        }
    }

    /// Inject dummy burst packets to match the target burst pattern.
    fn inject_burst_packets(&mut self) -> Result<(), ObfuscationError> {
        let burst_size = self.active_pattern.sample_burst_size();
        let mut rng = rand::thread_rng();

        // Only inject occasionally (1% of the time per call)
        if !rng.gen_bool(0.01) {
            return Ok(());
        }

        // Create dummy packets that look like encrypted video data
        for _ in 0..burst_size.min(3) {
            let size = self.active_pattern.sample_packet_size();
            let mut dummy = vec![0u8; size];
            rng.fill(&mut dummy[..]);

            self.stats.dummy_packets_injected += 1;
            trace!("Injected dummy packet: {} bytes", size);
        }

        Ok(())
    }

    /// Check if a packet is a tunnel handshake that should bypass shaping.
    fn is_tunnel_handshake(&self, data: &[u8]) -> bool {
        // WireGuard handshake initiation starts with message type 1
        // and is exactly 148 bytes (IPv4) or 180 bytes (IPv6)
        if data.len() == 148 || data.len() == 180 {
            if data.first() == Some(&1) {
                return true;
            }
        }

        // WireGuard handshake response: message type 2, 92 bytes
        if data.len() == 92 && data.first() == Some(&2) {
            return true;
        }

        false
    }

    /// Buffer a packet for delayed transmission.
    pub fn buffer_packet(&mut self, data: Vec<u8>, priority: u8, is_handshake: bool) {
        // Check if buffer is full
        if self.buffer_bytes + data.len() > self.config.max_buffer_bytes {
            self.flush_buffer();
        }

        self.buffer_bytes += data.len();
        self.stats.max_buffer_occupancy = self.stats.max_buffer_occupancy.max(self.buffer_bytes);

        self.buffer.push_back(BufferedPacket {
            data,
            enqueued_at: Instant::now(),
            priority,
            is_handshake,
        });
    }

    /// Get packets that are ready to be sent.
    pub fn drain_ready_packets(&mut self) -> Vec<BufferedPacket> {
        let max_delay = Duration::from_millis(self.config.max_queuing_delay_ms as u64);
        let now = Instant::now();

        let mut ready = Vec::new();
        let mut remaining = VecDeque::new();

        while let Some(pkt) = self.buffer.pop_front() {
            // Priority packets are always ready
            if pkt.is_handshake || pkt.priority == 0 {
                ready.push(pkt);
                continue;
            }

            // Check if packet has exceeded maximum queuing delay
            if now.duration_since(pkt.enqueued_at) >= max_delay {
                ready.push(pkt);
                continue;
            }

            // Keep packet in buffer for now
            remaining.push_back(pkt);
        }

        self.buffer = remaining;
        self.buffer_bytes = self.buffer.iter().map(|p| p.data.len()).sum();

        ready
    }

    /// Flush the entire buffer, sending all packets immediately.
    fn flush_buffer(&mut self) {
        self.stats.buffer_flushes += 1;
        // In a real implementation, this would send all buffered packets
        // immediately without shaping, to prevent excessive latency.
        self.buffer.clear();
        self.buffer_bytes = 0;
    }

    /// Set a new traffic pattern (e.g., from GAN output).
    pub fn set_pattern(&mut self, pattern: TrafficPattern) {
        debug!("Traffic pattern changed to: {}", pattern.pattern_name);
        self.active_pattern = pattern;
    }

    /// Check if the shaper is currently active.
    pub async fn is_active(&self) -> bool {
        self.state.read().await.active
    }

    /// Shut down the shaper and flush any remaining buffered packets.
    pub async fn shutdown(&mut self) {
        self.flush_buffer();
        let mut state = self.state.write().await;
        state.active = false;
        state.mode = ShapingMode::Passthrough;
        debug!("TrafficShaper shutdown complete");
    }
}

/// Remove padding from a received packet.
///
/// This is the inverse of the padding operation in `shape_packet_size`.
/// The last 2 bytes of the packet contain the padding length.
pub fn strip_padding(data: &[u8]) -> Vec<u8> {
    if data.len() < 4 {
        return data.to_vec();
    }

    let len = data.len();
    let padding_len = u16::from_be_bytes([data[len - 2], data[len - 1]]) as usize;

    // Sanity check: padding length should be reasonable
    if padding_len == 0 || padding_len >= len {
        return data.to_vec();
    }

    let original_len = len - padding_len;
    data[..original_len].to_vec()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_video_streaming_pattern() {
        let pattern = TrafficPattern::video_streaming();
        assert_eq!(pattern.pattern_name, "https-video-streaming");

        // Sample multiple packet sizes
        for _ in 0..100 {
            let size = pattern.sample_packet_size();
            assert!(size >= 40 && size <= 1500);
        }
    }

    #[test]
    fn test_inter_arrival_timing() {
        let pattern = TrafficPattern::video_streaming();
        for _ in 0..100 {
            let delay = pattern.sample_inter_arrival();
            assert!(delay > Duration::ZERO);
        }
    }

    #[test]
    fn test_shaper_passthrough() {
        let mut shaper = TrafficShaper::new(IspProfile::Unknown);
        // Unknown ISP with no threat should passthrough
        let data = vec![1, 2, 3, 4, 5];
        // In passthrough mode, no shaping should be applied
        assert_eq!(shaper.config.shaping_intensity, 0.0);
    }

    #[test]
    fn test_padding_add_and_strip() {
        let original = vec![0xDE, 0xAD, 0xBE, 0xEF];
        let mut shaper = TrafficShaper::new(IspProfile::Mci);
        shaper.config.padding_enabled = true;

        let padded = shaper
            .shape_packet_size(&original, ShapingMode::Full)
            .unwrap();
        assert!(
            padded.len() > original.len(),
            "Padded packet should be larger"
        );

        let stripped = strip_padding(&padded);
        assert_eq!(stripped, original, "Stripped padding should match original");
    }

    #[test]
    fn test_buffer_management() {
        let mut shaper = TrafficShaper::new(IspProfile::Mci);
        shaper.config.max_buffer_bytes = 100;

        // Buffer a packet
        shaper.buffer_packet(vec![0u8; 50], 128, false);
        assert_eq!(shaper.buffer.len(), 1);

        // Buffer exceeds limit - should flush
        shaper.buffer_packet(vec![0u8; 60], 128, false);
        // After flush, buffer should be cleared
        assert_eq!(shaper.buffer.len(), 0);
        assert_eq!(shaper.stats.buffer_flushes, 1);
    }

    #[test]
    fn test_handshake_bypass() {
        let shaper = TrafficShaper::new(IspProfile::Mci);

        // WireGuard handshake initiation
        let mut wg_init = vec![1u8]; // Message type 1
        wg_init.resize(148, 0);
        assert!(shaper.is_tunnel_handshake(&wg_init));

        // WireGuard handshake response
        let mut wg_resp = vec![2u8]; // Message type 2
        wg_resp.resize(92, 0);
        assert!(shaper.is_tunnel_handshake(&wg_resp));

        // Regular data packet
        let data = vec![4u8; 100]; // Message type 4 = data
        assert!(!shaper.is_tunnel_handshake(&data));
    }

    #[test]
    fn test_pattern_selection() {
        let p1 = TrafficShaper::select_pattern(IspProfile::Mci);
        assert_eq!(p1.pattern_name, "https-video-streaming");

        let p2 = TrafficShaper::select_pattern(IspProfile::Irancell);
        assert_eq!(p2.pattern_name, "https-web-browsing");
    }
}
