/// License controller — first-launch gate, fail-closed activation, secure
/// caching. Mirrors the Rust `verify.rs` flow through the FFI core.
library;

import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:flutter_secure_storage/flutter_secure_storage.dart';

import 'vor_ffi.dart';

class VerificationReport {
  final bool ok;
  final String? errorCode;
  final String? error;
  final String? licenseId;
  final String? tier;
  final String? keyId;
  final int? expiresAt;
  final int? daysRemaining;
  final List<String>? entitlements;

  const VerificationReport({
    required this.ok,
    this.errorCode,
    this.error,
    this.licenseId,
    this.tier,
    this.keyId,
    this.expiresAt,
    this.daysRemaining,
    this.entitlements,
  });

  factory VerificationReport.fromCore(Map<String, dynamic> j) => VerificationReport(
        ok: j['ok'] == true,
        errorCode: j['error_code'] as String?,
        error: j['error'] as String?,
        licenseId: j['license_id'] as String?,
        tier: j['tier'] as String?,
        keyId: j['key_id'] as String?,
        expiresAt: j['expires_at'] as int?,
        daysRemaining: j['days_remaining'] as int?,
        entitlements: (j['entitlements'] as List?)?.cast<String>(),
      );
}

/// Trusted public-key set shipped inside the client bundle.
/// In production this file is generated by the License Manager
/// (`vor-lictool export-public`) and embedded at build time.
class TrustedKeys {
  static const String assetPath = 'assets/keys/vor_trusted_keys.json';

  static Future<Map<String, dynamic>> load() async {
    try {
      final raw = await rootBundle.loadString(assetPath);
      return jsonDecode(raw) as Map<String, dynamic>;
    } catch (_) {
      // Development fallback: empty trust store → every license rejected
      // (fail-closed) until the operator ships a real bundle.
      return const {
        'trusted_version': 1,
        'keys': <String, dynamic>{},
      };
    }
  }
}

/// Errors are surfaced verbatim to the gate UI (fail-closed, typed).
class LicenseController extends ChangeNotifier {
  static const _kActivated = 'vor.activated.envelope';

  final _secure = const FlutterSecureStorage(
    aOptions: AndroidOptions(encryptedSharedPreferences: true),
  );

  VerificationReport? lastReport;
  bool activated = false;
  String? _cachedEnvelope;
  List<String> revoked = const [];

  Future<void> loadRevocationList() async {
    try {
      final raw = await DefaultAssetBundle.of(_ctx!).loadString('assets/keys/revoked.json');
      revoked = (jsonDecode(raw) as List).cast<String>();
    } catch (_) {
      revoked = const [];
    }
  }

  int get _now => DateTime.now().millisecondsSinceEpoch ~/ 1000;

  /// Verify envelope + persist activation. Returns the typed report.
  Future<VerificationReport> activate(String envelope) async {
    final trusted = await TrustedKeys.load();
    final report = VerificationReport.fromCore(VorCore.I.verifyLicense(
      envelope: envelope.trim(),
      trustedKeys: trusted,
      nowSecs: _now,
      hwid: VorCore.I.hwid,
    ));
    lastReport = report;
    if (report.ok) {
      _cachedEnvelope = envelope.trim();
      await _secure.write(key: _kActivated, value: envelope.trim());
      activated = true;
    } else {
      activated = false;
    }
    notifyListeners();
    return report;
  }

  /// Boot-time re-verification of the cached license (fail-closed).
  Future<bool> restoreSession() async {
    final env = await _secure.read(key: _kActivated);
    if (env == null || env.isEmpty) return false;
    final report = await activate(env);
    return report.ok;
  }

  Future<void> deactivate() async {
    await _secure.delete(key: _kActivated);
    _cachedEnvelope = null;
    activated = false;
    lastReport = null;
    notifyListeners();
  }

  String? get cachedEnvelope => _cachedEnvelope;
}
