// Package gtunnel implements a domain-fronted relay proxy: a local HTTP/HTTPS
// proxy whose every request is wrapped in JSON and sent — disguised as ordinary
// traffic to an allowed front domain (e.g. www.google.com) — to a Google Apps
// Script web app, which forwards it to a Cloudflare Worker that performs the
// real fetch and returns the response. To the network/DPI the connection looks
// like a normal TLS session to the front domain.
//
//	browser → local proxy → [TLS SNI=front, Host=script.google.com] → GAS → CF Worker → target
//
// This is an original, self-contained implementation of that mechanism (the
// relay JSON shape {k,m,u,h,b,ct,r} → {s,h,b}); the matching worker.js and
// Code.gs are generated by this package so the user never touches any upstream
// repo. HTTPS is handled by an on-the-fly MITM using a local CA the user
// installs once. Streaming/WebSocket is not supported (the relay is
// request/response only).
package gtunnel

import (
	"bufio"
	"bytes"
	"context"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/base64"
	"encoding/json"
	"encoding/pem"
	"errors"
	"fmt"
	"io"
	"math/big"
	"net"
	"net/http"
	"strings"
	"sync"
	"time"
)

// LogFunc receives log lines.
type LogFunc func(msg, level string)

// Config holds the relay parameters.
type Config struct {
	FrontIP    string // edge IP to dial, e.g. 216.239.38.120 (Google)
	FrontSNI   string // TLS SNI shown to the network, e.g. www.google.com
	FrontHost  string // real Host header, e.g. script.google.com
	ScriptID   string // GAS deployment id (…/macros/s/<id>/exec)
	AuthKey    string // shared secret matching Code.gs
	WorkerURL  string // for reference / script generation only
	ListenHost string
	ListenPort int
}

// hop-by-hop headers never forwarded.
var hopHeaders = map[string]bool{
	"connection": true, "proxy-connection": true, "keep-alive": true,
	"transfer-encoding": true, "te": true, "trailer": true, "upgrade": true,
	"proxy-authorization": true, "proxy-authenticate": true,
}

// Runner supervises the local proxy.
type Runner struct {
	mu      sync.Mutex
	ln      net.Listener
	running bool
	cfg     Config
	log     LogFunc
	client  *http.Client

	caCert    *x509.Certificate
	caKey     *ecdsa.PrivateKey
	caPEM     []byte
	leafMu    sync.Mutex
	leafCache map[string]*tls.Certificate

	reqs    int64
	errs    int64
	caPath  string
	keyPath string
}

// NewRunner builds a runner that logs via log.
func NewRunner(log LogFunc) *Runner {
	if log == nil {
		log = func(string, string) {}
	}
	return &Runner{log: log, leafCache: map[string]*tls.Certificate{}}
}

// caStore lets the server hand us load/save hooks for the CA (persisted beside
// the app config so the user trusts it only once).
type caStore struct {
	load func(name string) ([]byte, error)
	save func(name string, data []byte) error
}

var store caStore

// SetStore wires persistence callbacks (called once at startup).
func SetStore(load func(string) ([]byte, error), save func(string, []byte) error) {
	store = caStore{load: load, save: save}
}

// fronting transport: dial the front IP with the front SNI for *every* host, so
// requests to script.google.com / script.googleusercontent.com all ride the
// same allowed-looking TLS session.
func (r *Runner) buildClient() *http.Client {
	cfg := r.cfg
	tr := &http.Transport{
		ForceAttemptHTTP2: false,
		DialTLSContext: func(ctx context.Context, network, addr string) (net.Conn, error) {
			d := net.Dialer{Timeout: 15 * time.Second}
			raw, err := d.DialContext(ctx, "tcp", net.JoinHostPort(cfg.FrontIP, "443"))
			if err != nil {
				return nil, err
			}
			tconn := tls.Client(raw, &tls.Config{ServerName: cfg.FrontSNI, MinVersion: tls.VersionTLS12})
			if err := tconn.HandshakeContext(ctx); err != nil {
				raw.Close()
				return nil, err
			}
			return tconn, nil
		},
		MaxIdleConns:        20,
		IdleConnTimeout:     60 * time.Second,
		TLSHandshakeTimeout: 15 * time.Second,
	}
	return &http.Client{
		Transport: tr,
		Timeout:   45 * time.Second,
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			if len(via) >= 5 {
				return errors.New("too many redirects")
			}
			return nil
		},
	}
}

// relayResp is the GAS/Worker reply.
type relayResp struct {
	S int               `json:"s"`
	H map[string]string `json:"h"`
	B string            `json:"b"`
	E string            `json:"e"`
}

// relay sends one request through the front→GAS→Worker chain.
func (r *Runner) relay(method, urlStr string, header http.Header, body []byte) (*relayResp, error) {
	hmap := map[string]string{}
	for k, vs := range header {
		lk := strings.ToLower(k)
		if hopHeaders[lk] || lk == "host" || lk == "content-length" {
			continue
		}
		if len(vs) > 0 {
			hmap[k] = vs[0]
		}
	}
	payload := map[string]any{
		"k": r.cfg.AuthKey,
		"m": strings.ToUpper(method),
		"u": urlStr,
		"h": hmap,
		"r": true,
	}
	if len(body) > 0 {
		payload["b"] = base64.StdEncoding.EncodeToString(body)
		if ct := header.Get("Content-Type"); ct != "" {
			payload["ct"] = ct
		}
	}
	jb, _ := json.Marshal(payload)
	endpoint := "https://" + r.cfg.FrontHost + "/macros/s/" + r.cfg.ScriptID + "/exec"
	req, err := http.NewRequest("POST", endpoint, bytes.NewReader(jb))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("User-Agent", "Mozilla/5.0")
	resp, err := r.client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	raw, _ := io.ReadAll(io.LimitReader(resp.Body, 40<<20))
	var out relayResp
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, fmt.Errorf("relay decode (status %d): %s", resp.StatusCode, truncate(string(raw), 120))
	}
	if out.E != "" {
		return nil, errors.New("relay: " + out.E)
	}
	return &out, nil
}

// writeRelayResponse writes a relayResp to an HTTP-style writer.
func writeRelayResponse(w io.Writer, rr *relayResp, httpVer string) error {
	body, _ := base64.StdEncoding.DecodeString(rr.B)
	var b strings.Builder
	status := rr.S
	if status == 0 {
		status = 200
	}
	fmt.Fprintf(&b, "%s %d %s\r\n", httpVer, status, http.StatusText(status))
	hasLen := false
	for k, v := range rr.H {
		lk := strings.ToLower(k)
		if hopHeaders[lk] || lk == "transfer-encoding" {
			continue
		}
		if lk == "content-length" {
			hasLen = true
		}
		fmt.Fprintf(&b, "%s: %s\r\n", k, v)
	}
	if !hasLen {
		fmt.Fprintf(&b, "Content-Length: %d\r\n", len(body))
	}
	b.WriteString("Connection: close\r\n\r\n")
	if _, err := io.WriteString(w, b.String()); err != nil {
		return err
	}
	_, err := w.Write(body)
	return err
}

// handle is the proxy entrypoint.
func (r *Runner) handle(conn net.Conn) {
	defer conn.Close()
	conn.SetDeadline(time.Now().Add(60 * time.Second))
	br := bufio.NewReader(conn)
	req, err := http.ReadRequest(br)
	if err != nil {
		return
	}
	if req.Method == http.MethodConnect {
		r.handleConnect(conn, br, req)
		return
	}
	// Plain HTTP — relay directly.
	body, _ := io.ReadAll(req.Body)
	r.bump(true)
	rr, err := r.relay(req.Method, req.URL.String(), req.Header, body)
	if err != nil {
		r.bump(false)
		io.WriteString(conn, "HTTP/1.1 502 Bad Gateway\r\nContent-Length: 0\r\nConnection: close\r\n\r\n")
		return
	}
	_ = writeRelayResponse(conn, rr, "HTTP/1.1")
}

// handleConnect performs MITM for HTTPS: it answers 200 to CONNECT, presents a
// leaf cert for the host signed by our local CA, then relays each decrypted
// request through the chain.
func (r *Runner) handleConnect(conn net.Conn, br *bufio.Reader, req *http.Request) {
	host := req.URL.Hostname()
	port := req.URL.Port()
	if port == "" {
		port = "443"
	}
	if _, err := io.WriteString(conn, "HTTP/1.1 200 Connection Established\r\n\r\n"); err != nil {
		return
	}
	leaf, err := r.leafFor(host)
	if err != nil {
		return
	}
	tconn := tls.Server(conn, &tls.Config{
		Certificates: []tls.Certificate{*leaf},
		MinVersion:   tls.VersionTLS12,
	})
	if err := tconn.Handshake(); err != nil {
		return
	}
	defer tconn.Close()
	cbr := bufio.NewReader(tconn)
	for {
		tconn.SetDeadline(time.Now().Add(60 * time.Second))
		hreq, err := http.ReadRequest(cbr)
		if err != nil {
			return
		}
		body, _ := io.ReadAll(hreq.Body)
		scheme := "https://"
		hostport := host
		if port != "443" {
			hostport = net.JoinHostPort(host, port)
		}
		fullURL := scheme + hostport + hreq.URL.RequestURI()
		r.bump(true)
		rr, err := r.relay(hreq.Method, fullURL, hreq.Header, body)
		if err != nil {
			r.bump(false)
			io.WriteString(tconn, "HTTP/1.1 502 Bad Gateway\r\nContent-Length: 0\r\nConnection: close\r\n\r\n")
			return
		}
		if err := writeRelayResponse(tconn, rr, "HTTP/1.1"); err != nil {
			return
		}
		// We send Connection: close, so end after one request.
		return
	}
}

func (r *Runner) bump(req bool) {
	r.mu.Lock()
	if req {
		r.reqs++
	} else {
		r.errs++
	}
	r.mu.Unlock()
}

// ---- local CA + per-host leaf certs (MITM) --------------------------------

func (r *Runner) ensureCA() error {
	if r.caCert != nil {
		return nil
	}
	// Try to load a persisted CA so the user trusts it only once.
	if store.load != nil {
		certPEM, e1 := store.load("v2rayez-gtun-ca.pem")
		keyPEM, e2 := store.load("v2rayez-gtun-ca.key")
		if e1 == nil && e2 == nil && len(certPEM) > 0 && len(keyPEM) > 0 {
			if err := r.loadCA(certPEM, keyPEM); err == nil {
				return nil
			}
		}
	}
	// Generate a fresh CA.
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return err
	}
	serial, _ := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	tmpl := x509.Certificate{
		SerialNumber:          serial,
		Subject:               pkix.Name{CommonName: "V2RayEz Google Tunnel CA", Organization: []string{"V2RayEz"}},
		NotBefore:             time.Now().Add(-time.Hour),
		NotAfter:              time.Now().AddDate(10, 0, 0),
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageDigitalSignature,
		BasicConstraintsValid: true,
		IsCA:                  true,
		MaxPathLenZero:        true,
	}
	der, err := x509.CreateCertificate(rand.Reader, &tmpl, &tmpl, &key.PublicKey, key)
	if err != nil {
		return err
	}
	cert, _ := x509.ParseCertificate(der)
	r.caCert = cert
	r.caKey = key
	r.caPEM = pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der})
	keyDER, _ := x509.MarshalECPrivateKey(key)
	keyPEM := pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: keyDER})
	if store.save != nil {
		_ = store.save("v2rayez-gtun-ca.pem", r.caPEM)
		_ = store.save("v2rayez-gtun-ca.key", keyPEM)
	}
	return nil
}

func (r *Runner) loadCA(certPEM, keyPEM []byte) error {
	cb, _ := pem.Decode(certPEM)
	kb, _ := pem.Decode(keyPEM)
	if cb == nil || kb == nil {
		return errors.New("bad CA pem")
	}
	cert, err := x509.ParseCertificate(cb.Bytes)
	if err != nil {
		return err
	}
	key, err := x509.ParseECPrivateKey(kb.Bytes)
	if err != nil {
		return err
	}
	r.caCert = cert
	r.caKey = key
	r.caPEM = certPEM
	return nil
}

func (r *Runner) leafFor(host string) (*tls.Certificate, error) {
	r.leafMu.Lock()
	defer r.leafMu.Unlock()
	if c, ok := r.leafCache[host]; ok {
		return c, nil
	}
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, err
	}
	serial, _ := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	tmpl := x509.Certificate{
		SerialNumber: serial,
		Subject:      pkix.Name{CommonName: host},
		NotBefore:    time.Now().Add(-time.Hour),
		NotAfter:     time.Now().AddDate(2, 0, 0),
		KeyUsage:     x509.KeyUsageDigitalSignature,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
	}
	if ip := net.ParseIP(host); ip != nil {
		tmpl.IPAddresses = []net.IP{ip}
	} else {
		tmpl.DNSNames = []string{host}
	}
	der, err := x509.CreateCertificate(rand.Reader, &tmpl, r.caCert, &key.PublicKey, r.caKey)
	if err != nil {
		return nil, err
	}
	leaf := &tls.Certificate{Certificate: [][]byte{der, r.caCert.Raw}, PrivateKey: key}
	r.leafCache[host] = leaf
	return leaf, nil
}

// CAPEM returns the CA certificate (PEM) for the user to install.
func (r *Runner) CAPEM() []byte {
	r.mu.Lock()
	defer r.mu.Unlock()
	return r.caPEM
}

// ---- lifecycle ------------------------------------------------------------

// Start validates config, ensures the CA, and begins accepting on the proxy port.
func (r *Runner) Start(cfg Config) error {
	r.mu.Lock()
	defer r.mu.Unlock()
	if r.running {
		r.stopLocked()
	}
	if strings.TrimSpace(cfg.ScriptID) == "" {
		return errors.New("Apps Script deployment ID is required")
	}
	if strings.TrimSpace(cfg.AuthKey) == "" {
		return errors.New("auth key is required (must match your Code.gs)")
	}
	if cfg.FrontIP == "" {
		cfg.FrontIP = "216.239.38.120"
	}
	if cfg.FrontSNI == "" {
		cfg.FrontSNI = "www.google.com"
	}
	if cfg.FrontHost == "" {
		cfg.FrontHost = "script.google.com"
	}
	if cfg.ListenHost == "" {
		cfg.ListenHost = "127.0.0.1"
	}
	if cfg.ListenPort == 0 {
		cfg.ListenPort = 8086
	}
	r.cfg = cfg
	if err := r.ensureCA(); err != nil {
		return errors.New("CA: " + err.Error())
	}
	r.client = r.buildClient()
	addr := net.JoinHostPort(cfg.ListenHost, fmt.Sprintf("%d", cfg.ListenPort))
	ln, err := net.Listen("tcp", addr)
	if err != nil {
		return err
	}
	r.ln = ln
	r.running = true
	r.reqs, r.errs = 0, 0
	r.log(fmt.Sprintf("Google Tunnel proxy on http://%s (front %s via %s)", addr, cfg.FrontSNI, cfg.FrontIP), "OK")
	go func(l net.Listener) {
		for {
			c, err := l.Accept()
			if err != nil {
				return
			}
			go r.handle(c)
		}
	}(ln)
	return nil
}

func (r *Runner) stopLocked() {
	if r.ln != nil {
		r.ln.Close()
		r.ln = nil
	}
	r.running = false
}

// Stop closes the proxy.
func (r *Runner) Stop() {
	r.mu.Lock()
	defer r.mu.Unlock()
	if r.running {
		r.log("Google Tunnel stopped", "DIM")
	}
	r.stopLocked()
}

// Running reports state.
func (r *Runner) Running() bool {
	r.mu.Lock()
	defer r.mu.Unlock()
	return r.running
}

// Status returns a UI snapshot.
func (r *Runner) Status() map[string]any {
	r.mu.Lock()
	defer r.mu.Unlock()
	port := 0
	if r.running {
		port = r.cfg.ListenPort
	}
	return map[string]any{
		"running":  r.running,
		"port":     port,
		"front":    r.cfg.FrontSNI,
		"requests": r.reqs,
		"errors":   r.errs,
		"has_ca":   r.caPEM != nil,
	}
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "…"
}
