// ==============================================================================
// MasterDnsVPN
// Author: MasterkinG32
// Github: https://github.com/masterking32
// Year: 2026
// ==============================================================================

package enums

const (
	// MTU discovery packets
	PACKET_MTU_UP_REQ   = 0x01
	PACKET_MTU_UP_RES   = 0x02
	PACKET_MTU_DOWN_REQ = 0x03
	PACKET_MTU_DOWN_RES = 0x04

	// Session management packets
	PACKET_SESSION_INIT   = 0x05
	PACKET_SESSION_ACCEPT = 0x06
	PACKET_PING           = 0x07
	PACKET_PONG           = 0x08

	// Stream transport packets
	PACKET_STREAM_SYN              = 0x09
	PACKET_STREAM_SYN_ACK          = 0x0A // 10
	PACKET_STREAM_CONNECTED        = 0x0B // 11
	PACKET_STREAM_CONNECTED_ACK    = 0x0C // 12
	PACKET_STREAM_CONNECT_FAIL     = 0x0D // 13
	PACKET_STREAM_CONNECT_FAIL_ACK = 0x0E // 14
	PACKET_STREAM_DATA             = 0x0F // 15
	PACKET_STREAM_DATA_ACK         = 0x10 // 16
	PACKET_STREAM_DATA_NACK        = 0x11 // 17
	PACKET_STREAM_RESEND           = 0x12 // 18
	PACKET_PACKED_CONTROL_BLOCKS   = 0x13 // 19
	PACKET_STREAM_CLOSE_WRITE      = 0x14 // 20
	PACKET_STREAM_CLOSE_WRITE_ACK  = 0x15 // 21
	PACKET_STREAM_CLOSE_READ       = 0x16 // 22
	PACKET_STREAM_CLOSE_READ_ACK   = 0x17 // 23
	PACKET_STREAM_RST              = 0x18 // 24
	PACKET_STREAM_RST_ACK          = 0x19 // 25

	// SOCKS5 stream setup packets
	PACKET_SOCKS5_SYN     = 0x1A // 26
	PACKET_SOCKS5_SYN_ACK = 0x1B // 27

	// SOCKS5 result packets
	PACKET_SOCKS5_CONNECT_FAIL                 = 0x1C // 28
	PACKET_SOCKS5_CONNECT_FAIL_ACK             = 0x1D // 29
	PACKET_SOCKS5_RULESET_DENIED               = 0x1E // 30
	PACKET_SOCKS5_RULESET_DENIED_ACK           = 0x1F // 31
	PACKET_SOCKS5_NETWORK_UNREACHABLE          = 0x20 // 32
	PACKET_SOCKS5_NETWORK_UNREACHABLE_ACK      = 0x21 // 33
	PACKET_SOCKS5_HOST_UNREACHABLE             = 0x22 // 34
	PACKET_SOCKS5_HOST_UNREACHABLE_ACK         = 0x23 // 35
	PACKET_SOCKS5_CONNECTION_REFUSED           = 0x24 // 36
	PACKET_SOCKS5_CONNECTION_REFUSED_ACK       = 0x25 // 37
	PACKET_SOCKS5_TTL_EXPIRED                  = 0x26 // 38
	PACKET_SOCKS5_TTL_EXPIRED_ACK              = 0x27 // 39
	PACKET_SOCKS5_COMMAND_UNSUPPORTED          = 0x28 // 40
	PACKET_SOCKS5_COMMAND_UNSUPPORTED_ACK      = 0x29 // 41
	PACKET_SOCKS5_ADDRESS_TYPE_UNSUPPORTED     = 0x2A // 42
	PACKET_SOCKS5_ADDRESS_TYPE_UNSUPPORTED_ACK = 0x2B // 43
	PACKET_SOCKS5_AUTH_FAILED                  = 0x2C // 44
	PACKET_SOCKS5_AUTH_FAILED_ACK              = 0x2D // 45
	PACKET_SOCKS5_UPSTREAM_UNAVAILABLE         = 0x2E // 46
	PACKET_SOCKS5_UPSTREAM_UNAVAILABLE_ACK     = 0x2F // 47
	PACKET_SOCKS5_CONNECTED                    = 0x30 // 48
	PACKET_SOCKS5_CONNECTED_ACK                = 0x31 // 49

	// DNS tunnel packets
	PACKET_DNS_QUERY_REQ     = 0x32 // 50
	PACKET_DNS_QUERY_RES     = 0x33 // 51
	PACKET_DNS_QUERY_REQ_ACK = 0x34 // 52
	PACKET_DNS_QUERY_RES_ACK = 0x35 // 53

	// Session control packets
	PACKET_SESSION_CLOSE = 0x36 // 54
	PACKET_SESSION_BUSY  = 0x37 // 55

	// Generic error packets
	PACKET_ERROR_DROP = 0xFF // 255
)

const (
	STREAM_STATE_OPEN               = 1
	STREAM_STATE_HALF_CLOSED_LOCAL  = 2
	STREAM_STATE_HALF_CLOSED_REMOTE = 3
	STREAM_STATE_DRAINING           = 4
	STREAM_STATE_CLOSING            = 5
	STREAM_STATE_TIME_WAIT          = 6
	STREAM_STATE_RESET              = 7
	STREAM_STATE_CLOSED             = 8
)

const (
	DNS_RECORD_TYPE_A           = 1
	DNS_RECORD_TYPE_NS          = 2
	DNS_RECORD_TYPE_MD          = 3
	DNS_RECORD_TYPE_MF          = 4
	DNS_RECORD_TYPE_CNAME       = 5
	DNS_RECORD_TYPE_SOA         = 6
	DNS_RECORD_TYPE_MB          = 7
	DNS_RECORD_TYPE_MG          = 8
	DNS_RECORD_TYPE_MR          = 9
	DNS_RECORD_TYPE_NULL        = 10
	DNS_RECORD_TYPE_WKS         = 11
	DNS_RECORD_TYPE_PTR         = 12
	DNS_RECORD_TYPE_HINFO       = 13
	DNS_RECORD_TYPE_MINFO       = 14
	DNS_RECORD_TYPE_MX          = 15
	DNS_RECORD_TYPE_TXT         = 16
	DNS_RECORD_TYPE_RP          = 17
	DNS_RECORD_TYPE_AFSDB       = 18
	DNS_RECORD_TYPE_X25         = 19
	DNS_RECORD_TYPE_ISDN        = 20
	DNS_RECORD_TYPE_RT          = 21
	DNS_RECORD_TYPE_NSAP        = 22
	DNS_RECORD_TYPE_NSAP_PTR    = 23
	DNS_RECORD_TYPE_SIG         = 24
	DNS_RECORD_TYPE_KEY         = 25
	DNS_RECORD_TYPE_PX          = 26
	DNS_RECORD_TYPE_GPOS        = 27
	DNS_RECORD_TYPE_AAAA        = 28
	DNS_RECORD_TYPE_LOC         = 29
	DNS_RECORD_TYPE_NXT         = 30
	DNS_RECORD_TYPE_EID         = 31
	DNS_RECORD_TYPE_NIMLOC      = 32
	DNS_RECORD_TYPE_SRV         = 33
	DNS_RECORD_TYPE_ATMA        = 34
	DNS_RECORD_TYPE_NAPTR       = 35
	DNS_RECORD_TYPE_KX          = 36
	DNS_RECORD_TYPE_CERT        = 37
	DNS_RECORD_TYPE_A6          = 38
	DNS_RECORD_TYPE_DNAME       = 39
	DNS_RECORD_TYPE_SINK        = 40
	DNS_RECORD_TYPE_OPT         = 41
	DNS_RECORD_TYPE_APL         = 42
	DNS_RECORD_TYPE_DS          = 43
	DNS_RECORD_TYPE_SSHFP       = 44
	DNS_RECORD_TYPE_IPSECKEY    = 45
	DNS_RECORD_TYPE_RRSIG       = 46
	DNS_RECORD_TYPE_NSEC        = 47
	DNS_RECORD_TYPE_DNSKEY      = 48
	DNS_RECORD_TYPE_DHCID       = 49
	DNS_RECORD_TYPE_NSEC3       = 50
	DNS_RECORD_TYPE_NSEC3_PARAM = 51
	DNS_RECORD_TYPE_TLSA        = 52
	DNS_RECORD_TYPE_SMIMEA      = 53
	DNS_RECORD_TYPE_HIP         = 55
	DNS_RECORD_TYPE_NINFO       = 56
	DNS_RECORD_TYPE_RKEY        = 57
	DNS_RECORD_TYPE_TALINK      = 58
	DNS_RECORD_TYPE_CDS         = 59
	DNS_RECORD_TYPE_CDNSKEY     = 60
	DNS_RECORD_TYPE_OPENPGPKEY  = 61
	DNS_RECORD_TYPE_CSYNC       = 62
	DNS_RECORD_TYPE_ZONEMD      = 63
	DNS_RECORD_TYPE_SVCB        = 64
	DNS_RECORD_TYPE_HTTPS       = 65
	DNS_RECORD_TYPE_DSYNC       = 66
	DNS_RECORD_TYPE_HHIT        = 67
	DNS_RECORD_TYPE_BRID        = 68
	DNS_RECORD_TYPE_SPF         = 99
	DNS_RECORD_TYPE_UINFO       = 100
	DNS_RECORD_TYPE_UID         = 101
	DNS_RECORD_TYPE_GID         = 102
	DNS_RECORD_TYPE_UNSPEC      = 103
	DNS_RECORD_TYPE_NID         = 104
	DNS_RECORD_TYPE_L32         = 105
	DNS_RECORD_TYPE_L64         = 106
	DNS_RECORD_TYPE_LP          = 107
	DNS_RECORD_TYPE_EUI48       = 108
	DNS_RECORD_TYPE_EUI64       = 109
	DNS_RECORD_TYPE_NXNAME      = 128
	DNS_RECORD_TYPE_TKEY        = 249
	DNS_RECORD_TYPE_TSIG        = 250
	DNS_RECORD_TYPE_IXFR        = 251
	DNS_RECORD_TYPE_AXFR        = 252
	DNS_RECORD_TYPE_MAILB       = 253
	DNS_RECORD_TYPE_MAILA       = 254
	DNS_RECORD_TYPE_ANY         = 255
	DNS_RECORD_TYPE_URI         = 256
	DNS_RECORD_TYPE_CAA         = 257
	DNS_RECORD_TYPE_AVC         = 258
	DNS_RECORD_TYPE_DOA         = 259
	DNS_RECORD_TYPE_AMTRELAY    = 260
	DNS_RECORD_TYPE_RESINFO     = 261
	DNS_RECORD_TYPE_WALLET      = 262
	DNS_RECORD_TYPE_CLA         = 263
	DNS_RECORD_TYPE_IPN         = 264
	DNS_RECORD_TYPE_TA          = 32768
	DNS_RECORD_TYPE_DLV         = 32769
)

const (
	DNSR_CODE_NO_ERROR        = 0
	DNSR_CODE_FORMAT_ERROR    = 1
	DNSR_CODE_SERVER_FAILURE  = 2
	DNSR_CODE_NAME_ERROR      = 3
	DNSR_CODE_NOT_IMPLEMENTED = 4
	DNSR_CODE_REFUSED         = 5
	DNSR_CODE_YXDOMAIN        = 6
	DNSR_CODE_YXRRSET         = 7
	DNSR_CODE_NXRRSET         = 8
	DNSR_CODE_NOT_AUTHORIZED  = 9
	DNSR_CODE_NOT_ZONE        = 10
)

const (
	DNSQ_CLASS_IN  = 1
	DNSQ_CLASS_CS  = 2
	DNSQ_CLASS_CH  = 3
	DNSQ_CLASS_HS  = 4
	DNSQ_CLASS_ANY = 255
)
