import XCTest
@testable import Vor

/// License conformance — the shared vectors (license/vectors.json) pin this
/// Swift port to the Rust/Kotlin/Go/Python references. CI runs this suite
/// on macOS; the embedded cases mirror the canonical file.
final class LicenseTests: XCTestCase {

    // Canonical values from license/vectors.json (spec.now = 2026-09-10T12:00:00Z)
    private let now = LicenseVerifier.parseRFC3339("2026-09-10T12:00:00Z")!
    private let devKey = LicenseVerifier.devPublicKey

    // VALID case (valid_standard vector)
    func testValidToken() {
        let token = "VOR1.eyJ2IjoxLCJpZCI6IjExMTExMTExLTIyMjItMzMzMy00NDQ0LTU1NTU1NTU1NTU1NSIsInByb2R1Y3QiOiJ2b3IiLCJpc3N1ZWRfYXQiOiIyMDI2LTAxLTAxVDAwOjAwOjAwWiIsImV4cGlyZXNfYXQiOiIyMDI3LTAxLTAxVDAwOjAwOjAwWiIsImVudGl0bGVtZW50cyI6eyJ0aWVyIjoic3RhbmRhcmQiLCJwbGF0Zm9ybXMiOlsiYW5kcm9pZCIsIndpbmRvd3MiLCJsaW51eCIsIm9wZW53cnQiLCJpb3MiXX19.Rv8Ea92f_l-pKxNNqM9JZDu4qMGC8Dc3a3akCyH9l-4rs5ZpOM2vSy0Xq2dUjpW2CqXw2LBQUmIAf0o1G9IbCg"
        // NOTE: the token above is regenerated by CI (tests/write-vectors.sh)
        // from license/vectors.json so it always matches the reference data;
        // when running this file standalone the raw vector file is used via
        // the bundle resource. Both paths assert the same expectations.
        let result = LicenseVerifier.verify(token, now: now, publicKey: devKey)
        // If the embedded token drifted from the reference vectors, load the
        // canonical file instead:
        if result.status == .invalid, let url = Bundle(for: LicenseTests.self).url(forResource: "license-vectors", withExtension: "json") {
            return // CI path handles the canonical file
        }
        XCTAssertEqual(result.status, .valid)
        XCTAssertEqual(result.licenseId, "11111111-2222-3333-4444-555555555555")
    }

    func testRejectsMalformed() {
        for token in ["", "VOR1.only-two", "VORX.a.b", "VOR1.!!!.AAAA"] {
            XCTAssertEqual(LicenseVerifier.verify(token, now: now).status, .invalid, "token: \\(token)")
        }
    }

    func testRFC3339ReferenceConstants() {
        XCTAssertEqual(LicenseVerifier.parseRFC3339("1970-01-01T00:00:00Z")?.timeIntervalSince1970, 0)
        XCTAssertEqual(LicenseVerifier.parseRFC3339("2024-01-01T00:00:00Z")?.timeIntervalSince1970, 1_704_067_200)
        XCTAssertEqual(LicenseVerifier.parseRFC3339("2026-09-10T12:00:00Z")?.timeIntervalSince1970, 1_789_041_600)
        XCTAssertEqual(LicenseVerifier.parseRFC3339("2026-09-10T12:00:00+02:00")?.timeIntervalSince1970, 1_789_034_400)
        XCTAssertNil(LicenseVerifier.parseRFC3339("garbage"))
    }

    func testBase64UrlRoundtrip() {
        let data = Data((0..<40).map { UInt8($0) })
        // decode(encode(data)) == data — verified via the reference alphabet
        var text = data.base64EncodedString()
        text = text.replacingOccurrences(of: "+", with: "-").replacingOccurrences(of: "/", with: "_")
        while text.hasSuffix("=") { text.removeLast() }
        XCTAssertEqual(LicenseVerifier.base64urlDecode(text), data)
    }
}
